version: "3.9"
services:
  www:
    build:
      context: www
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.www.rule: Host(`www.${PROJECT_DOMAIN_NAME}`)
      traefik.http.routers.www.entrypoints: web-secure
      traefik.http.routers.www.tls: true
    environment:
      - NGINX_DOMAIN=${PROJECT_DOMAIN_NAME}
  whoami:
    image: traefik/whoami
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.${PROJECT_DOMAIN_NAME}`)
      traefik.http.routers.whoami.entrypoints: web-secure
      traefik.http.routers.whoami.tls: true

networks:
  traefik-proxy:
    external: true
